app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
from flask import abort, flash, redirect, render_template, url_for
from flask_login import login_required, current_user

from . import home
from .. import db
from ..models import Employee


@home.route('/')
def homepage():

    return render_template('home/index.html', title='Welcome to Excel Team')


@home.route('/dashboard')
@login_required
def dashboard():
    return render_template('home/dashboard.html', title='Dashboard')


@home.route('/admin/dashboard')
@login_required
def admin_dashboard():
    if not current_user.is_admin:
        abort(403)
    return render_template('home/admin_dashboard.html', title='Admin Dashboard')


@home.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():

    return render_template('home/profilepage.html', title='Employee Profile')

app/templates/home/admin_dashboard.html
{% extends "base.html" %} {% block title %}Admin Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Admin Dashboard</h1>
                    <h3>Manage your Employees</h3>
                    <br>
                    <br>
                    <a href="{{ url_for('admin.list_employees') }}" id="db">Employee Database</a>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/dashboard.html
{% extends "base.html" %} {% block title %}Dashboard{% endblock %} {% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Hello {{current_user.first_name}}</h1>
                    <h3>Welcome to Excel Team. Let's Get Started</h3>
                    </ul>
                    <br>
                    <br>
                    <a href="{{ url_for('home.profile') }}" id="profilebtn">View your profile</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/index.html
{% extends "base.html" %} {% block title %}Home{% endblock %} {% block body %}
<p id="message">
    Excel Team allows you to manage your team in a easy way. You have complete control over the details of the registered employees. Manage the roles,salary grades and departments of your employees without hassle in simple clicks.
</p>
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Excel Team</h1>
                    <h3>Manage your team in the most perfect way</h3>
                    </ul>
                    <br>
                    <br>
                    <a href="{{ url_for('auth.register') }}" id="out">New User? Let's Get Started!</a>
                    <br>
                    <br>
                    <br>
                    <a href="{{ url_for('auth.login') }}" id="in">Administrator Login</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/home/profilepage.html
{% extends "base.html" %} {% block title %}View Profile{% endblock %} {% block body %}
<div id="mainwrap">
    <img src="../../static/img/avatar.png" id="avatar">
    <p id="cname">{{current_user.first_name}} {{current_user.last_name}}</p>
    <p id="cusername" class="textcontent">@{{current_user.username}}</p>
    <br>
    <div> <span id="mail"><i class="fa fa-envelope"></i><a href="mailto:{{current_user.email}}">  {{current_user.email}}</a></span></div>
    <br>
    <div> <span id="roles"><i class="fa fa-vcard-o"></i>  {{current_user.role}}</span></div>
    <br>
    <div> <span id="depart"><i class="fa fa-building"></i>  {{current_user.department}}</span></div>
    <br>
    <div> <span id="depart"><i class="fa fa-dollar"></i> Pay Grade : {{current_user.grade}}</span></div>
</div>
{% endblock %}